USE [master]
GO

/****** Object:  Database [FoodSolution]    Script Date: 18/01/2020 09:01:57 م ******/
CREATE DATABASE [FoodSolution]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodSolution', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DAFRO\MSSQL\DATA\FoodSolution.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FoodSolution_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DAFRO\MSSQL\DATA\FoodSolution_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodSolution].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodSolution] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodSolution] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodSolution] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodSolution] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodSolution] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodSolution] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodSolution] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodSolution] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodSolution] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodSolution] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodSolution] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodSolution] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodSolution] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodSolution] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodSolution] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FoodSolution] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodSolution] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodSolution] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodSolution] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodSolution] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodSolution] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FoodSolution] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodSolution] SET RECOVERY FULL 
GO

ALTER DATABASE [FoodSolution] SET  MULTI_USER 
GO

ALTER DATABASE [FoodSolution] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodSolution] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodSolution] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FoodSolution] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FoodSolution] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FoodSolution] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FoodSolution] SET  READ_WRITE 
GO

