// <auto-generated />
namespace MemmbersMeals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RenameForiegnKeyMemmberID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameForiegnKeyMemmberID));
        
        string IMigrationMetadata.Id
        {
            get { return "202001181610247_RenameForiegnKeyMemmberID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
